version: '3.8'

services:

  redis_cache:
    image: redis:latest
    container_name: redis_cache
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --loglevel warning
    volumes:
      - ./cache:/data
    networks:
      - tg_bot

  db:
    image: postgres:latest
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
    ports:
      - '5432:5432'
    networks:
      - tg_bot

  bot:
    container_name: bot
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    command: python main.py
    env_file:
      - .env
    volumes:
      - ./:/app
    depends_on:
      - db
      - redis_cache
    networks:
      - tg_bot


volumes:
  pgdata:

networks:
  tg_bot:
    driver: bridge