version: "3.8"

services:
  bot:
    container_name: bot
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    command: python main.py
    env_file:
      - .env
    volumes:
      - ./:/app
    networks:
      - tg_bot

  redis_cache:
    image: redis:7.2.3-alpine
    container_name: redis_cache
    restart: always
    command: redis-server
    volumes:
      - ./cache:/data
    networks:
      - tg_bot


networks:
  tg_bot:
    driver: bridge